commit-msg:
  commands:
    commitlint:
      run: npx commitlint --edit {1}

pre-commit:
  parallel: true
  commands:
    prettier:
      run: npx prettier --write {staged_files}
      glob: "*.{ts,tsx,md}"
      stage_fixed: true

    lint:
      run: npm run lint
      glob: "*.{ts,tsx}"
      root: "."

    typecheck:
      run: npm run typecheck
      glob: "*.{ts,tsx}"
      root: "."
